version: "3.9"
services:
  app:
    build: .  # build時にDockerfileを使用
    volumes:
      - /mnt/c/Users/221032/DockerProject/test/desktop-tutorial/data:/app/data
      - /mnt/c/Users/221032/DockerProject/test/desktop-tutorial/models:/app/models  # モデル保存用ディレクトリ
      - /mnt/c/Users/221032/DockerProject/test/desktop-tutorial/scripts:/app/scripts
      - /mnt/c/Users/221032/DockerProject/test/desktop-tutorial/checkpoints:/app/checkpoints
    deploy: # GPUを使用するための設定
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # 使用するGPUの数
              capabilities: [gpu]
    stdin_open: true
    tty: true  # コンテナに対する入力を有効にし、標準入力と出力を使用可能にする
